### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by daliad007** [heap/heap-ios-sdk#13]
Hello,

At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs etc will need to provide a privacy manifest. Does Heap need to include this manifest?
Is this update on the roadmap for the team? The enforcement will start on May 2024, so we want to make sure we have enough time to update the SDK on our end, test and release.

Useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/videos/play/wwdc2023/10060/

Thank you,
Dalia

**Comment by maxchuquimia** [comment]
Hi @Heap, 

I would also like an update on this as 1st May is approaching quickly, cheers~

**Comment by MCeley** [comment]
The Heap Classic iOS SDK uses two restricted APIs that may require a declaration in the privacy manifest. When including the Heap Classic iOS SDK, you can add these declarations to your privacy manifest as described here: https://developers.heap.io/docs/ios-legacy#updating-your-privacy-manifest
