### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by Workshed** [heap/heap-ios-sdk#2]
Running an app containing Heap via Cocoapods on the iOS Simulator on Apple Silicon (M1) currently results in an error. Is this something that there is a plan to address?

```
ld: in <project path>/Pods/Heap/libHeap.a(HITelemetry.o), building for iOS Simulator, but linking in object file built for iOS, file '<project path>/Pods/Heap/libHeap.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by TekEffekt** [comment]
We're having the same issue over at Brads Deals.

**Comment by mashdup** [comment]
Hey all,

For those who are on Apple Silicon. I got this to work.

First make sure you have `arm64` in excluded architectures in the Build Settings in your targets

Then in your Podfile

add 'ONLY_ACTIVE_ARCH' and 'BUILD_LIBRARY_FOR_DISTRIBUTION' to the post_install step

```
post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
````

I hope this helps you all. I hope they update this SDK

**Comment by bnickel** [comment]
Apple Silicon support has been added as of 8.0.0.
