### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by dougdiego** [heap/heap-ios-sdk#3]
Can you add support for Swift Package manager?

**Comment by sukhrobkhakimov** [comment]
More than 2 months have passed but still no news.

**Comment by kristiant** [comment]
+1, looking forward to seeing SPM support

**Comment by pablonosh** [comment]
As it's been 5 months, I hope you don't mind if I do this..
@afrieder
@drob
@GedRap
@greghuels
@HeavyLivestock
@j0narch3r
@james727
@jamesnghiem
@jerryjvl	
@radiofreejohn
@talos
@timothyandrew

**Comment by khoi** [comment]
Since Heap SDK development has been pretty much stale and unresponsive. I'm now forced to build a heap client for our own macOS and watchOS application. Their support has been no help, if you're a developer and evaluating Heap, 1 word: don't

**Comment by jerryhjones** [comment]
Hey folks, apologies for the radio silence on this thread. We're working on updating our release procedures to keep things updated here. A tiny bit of backstory: this repo was originally created to work around a bug with CocoaPods descriptions and privately hosted sources. Going forward, it will also be the public repo for manifests for Swift Package Manager.

Swift Package Manger is supported as of Heap iOS SDK version 8, and is now the suggested way to install Heap. You'll just want to use this repo URL with SPM, and you should be all set!

Docs: Docs: https://developers.heap.io/docs/ios
Repo: https://github.com/heap/heap-ios-sdk
